spring.application.name=FriendsHub API
server.port=8060
# Datasource
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/friendshub_db}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgres}
# Hibernate
spring.jpa.hibernate.ddl-auto=validate
# Liquibase
spring.liquibase.url=${DATASOURCE_URL}
spring.liquibase.user=${DATASOURCE_USERNAME}
spring.liquibase.password=${DATASOURCE_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=36000000
# Converter
spring.jackson.mapper.accept-case-insensitive-enums=true
# Logs
logging.level.root=INFO
logging.level.com.zack.friendshub=INFO
# Telegram Bot Configuration
telegram.bot.username=${TELEGRAM_BOT_USERNAME:FriendsHubBot}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:8686819748:AAGco-2nP5LXyNSzjkpaf_0QnMZo-foj43U}
